Repository mehdihadeli/go-ecommerce-microservices, pull requests merged in 2023-08, with the labels that each got.

#71 fix: :bug: fix custom domain errors bug
  internal/services/order_service/internal/orders/exceptions/domain_exceptions/invalid_delivery_address_error.go
  internal/services/order_service/internal/orders/exceptions/domain_exceptions/invalid_email_error.go
  internal/services/order_service/internal/orders/exceptions/domain_exceptions/order_items_required_errors.go
  internal/services/order_service/internal/orders/exceptions/domain_exceptions/order_not_found_error.go
Labels: bug, patch

#74 refactor: add validate to command/query level
  .github/workflows/ci.yml
  .github/workflows/golangci-lint.yml
  internal/services/catalog_read_service/go.mod
  internal/services/catalog_read_service/go.sum
  internal/services/catalog_read_service/internal/products/features/creating_product/v1/commands/create_product.go
  internal/services/catalog_read_service/internal/products/features/deleting_products/v1/commands/delete_product.go
  internal/services/catalog_read_service/internal/products/features/deleting_products/v1/events/integration_events/external_events/product_deleted_consumer.go
  internal/services/catalog_read_service/internal/products/features/get_product_by_id/v1/endpoints/get_product_by_id_endpoint.go
  internal/services/catalog_read_service/internal/products/features/get_product_by_id/v1/queries/get_product_by_id.go
  internal/services/catalog_read_service/internal/products/features/searching_products/v1/endpoints/search_products_endpoint.go
  internal/services/catalog_read_service/internal/products/features/searching_products/v1/queries/search_products.go
  internal/services/catalog_read_service/internal/products/features/updating_products/v1/commands/update_product.go
  internal/services/catalog_read_service/internal/products/features/updating_products/v1/events/integration_events/external_events/product_updated_consumer.go
  internal/services/catalog_read_service/test/integration/products/features/deleting_product/v1/commands/delete_product_handler_test.go
  internal/services/catalog_read_service/test/integration/products/features/getting_product_by_id/v1/queries/get_product_by_id_handler_test.go
  internal/services/catalog_read_service/test/integration/products/features/updating_product/v1/commands/update_product_handler_test.go
  internal/services/catalog_write_service/go.mod
  internal/services/catalog_write_service/go.sum
  internal/services/catalog_write_service/internal/products/features/creating_product/v1/commands/create_product.go
  internal/services/catalog_write_service/internal/products/features/deleting_product/v1/commands/delete_product.go
  internal/services/catalog_write_service/internal/products/features/getting_product_by_id/v1/queries/get_product_by_id.go
  internal/services/catalog_write_service/internal/products/features/getting_products/v1/queries/get_products.go
  internal/services/catalog_write_service/internal/products/features/searching_product/v1/queries/search_products.go
  internal/services/catalog_write_service/internal/products/features/updating_product/v1/commands/update_product.go
  internal/services/order_service/go.mod
  internal/services/order_service/go.sum
  readme.md
  scripts/test.sh
Labels: enhancement, feature

#79 fix: :bug: go-testcontainer upgrade to latest version error
  .github/workflows/ci.yml
  internal/pkg/go.mod
  internal/pkg/go.sum
  internal/pkg/grpc/otel/tracing/utils.go
  internal/pkg/http/custom_echo/echo_server.go
  internal/pkg/http/custom_echo/middlewares/otel_tracer/otel_tracer_middleware.go
  internal/pkg/http/custom_echo/otel/tracing/utils.go
  internal/pkg/messaging/otel/tracing/consumer/consumer.go
  internal/pkg/messaging/otel/tracing/producer/producer.go
  internal/pkg/otel/tracing/tracing.go
  internal/pkg/rabbitmq/consumer/rabbitmq_consumer.go
  internal/pkg/rabbitmq/producer/rabbitmq_producer.go
  internal/pkg/test/containers/testcontainer/eventstoredb/eventstoredb_container.go
  internal/pkg/test/containers/testcontainer/gorm/gorm_container.go
  internal/pkg/test/containers/testcontainer/mongo/mongo_container.go
  internal/pkg/test/containers/testcontainer/postgrespxg/postgrespgx_container.go
  internal/pkg/test/containers/testcontainer/rabbitmq/rabbitmq_container.go
  internal/pkg/test/containers/testcontainer/redis/redis_container.go
  internal/services/catalog_read_service/go.mod
  internal/services/catalog_read_service/go.sum
  internal/services/catalog_write_service/go.mod
  internal/services/catalog_write_service/go.sum
  internal/services/catalog_write_service/internal/shared/test_fixtures/integration/integration_test_fixture.go
  internal/services/catalog_write_service/test/integration/products/data/repositories/pg_product_repository_integration_test.go
  internal/services/catalog_write_service/test/integration/products/data/uow/catalogs_unit_of_work_integration_test.go
  internal/services/order_service/go.mod
  internal/services/order_service/go.sum
  readme.md
Labels: bug, test, patch
